channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.13.0
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - lightgbm==4.6.0
  - matplotlib==3.10.3
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.2
  - psutil==7.0.0
  - pyarrow==15.0.2
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env
